---
title: "Aging Code"
author: "Elizabeth Chen"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#loading packages that will be used
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(beepr)
library(ggthemes)
library(splitstackshape)
library(tidyverse)
library(survival)
library(survminer)
library(finalfit)
setwd("~/Documents/SSD_Data") #folder file is in

group_data <- read.csv('Aging.csv')
```

```{r checking group data}
head(group_data)
```

```{r making individuals their own rows}
death_records <- group_data %>%
  pivot_longer(cols = starts_with("DAY"), names_to = "day", names_prefix = "DAY", values_to = "count") %>%
  mutate(day = as.numeric(day)) %>%
  group_by(GROUP) %>%
  arrange(day) %>%
  mutate(deaths = lag(count, default = first(count)) - count) %>%
  filter(deaths > 0) %>%
  uncount(deaths) %>%
  group_by(GROUP) %>%
  mutate(id = paste0(GROUP, str_pad(row_number(), 2, pad = "0"))) %>%
  ungroup() %>%
  select(id, time = day)

print(death_records)
```

```{r extracting factor data from names}
death_records$line <- as.factor(substr(death_records$id, 1, 1))
death_records$treatment <- as.factor(substr(death_records$id, 2, 2))
death_records$sex <- as.factor(substr(death_records$id, 3, 3))
death_records$vial <- as.factor(substr(death_records$id, 4, 4))
death_records$status <- 1
head(death_records)
```

```{r visualizing dist}
ggplot(death_records, aes(x = time, color=treatment)) +
  geom_histogram(aes(y = ..density..), bins = 10) +
  geom_density() +
  facet_grid(line ~ sex)
```

```{r survival curves}
death_records <- death_records %>%
  mutate(line = factor(line, levels = c("O", "L", "H")))

coxph(Surv(time, status) ~ line * sex * treatment, data = death_records) %>% 
  anova()

explanatory <- c("line", "sex", "treatment")
dependent <- "Surv(time, status)"
death_records %>% 
    hr_plot(dependent, explanatory)

surv_obj <- Surv(time = death_records$time, event = death_records$status)
```

```{r}
ggsurvplot_facet(
  fit = survfit(Surv(time, status) ~ sex, data = death_records),
  data = death_records,
  facet.by = c("treatment", "line"),
  xlim = c(0, 75),
  short.panel.labs = TRUE,
  pval = TRUE,            
  conf.int = TRUE,        
  risk.table = TRUE,      
  palette = "jco",        
  ggtheme = theme_minimal()
)
```
